apiVersion: v1
kind: Service
metadata:
  name: diabetes-api-svc
  namespace: inference
spec:
  selector:
    app: diabetes-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
  type: NodePort
