apiVersion: v1
kind: Service
metadata:
  name: diabetes-ui-svc
  namespace: inference
spec:
  selector:
    app: diabetes-ui
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30801
  type: NodePort
